"""fouriax package."""

from fouriax.core.fft import fftconvolve
from fouriax.optics import (
    AmplitudeMaskLayer,
    ASMPropagator,
    AutoPropagator,
    ComplexMaskLayer,
    Field,
    FieldReadout,
    Grid,
    IntensitySensor,
    OpticalLayer,
    OpticalModule,
    PhaseMaskLayer,
    PropagationLayer,
    PropagationModel,
    Propagator,
    RSPropagator,
    Sensor,
    Spectrum,
    ThinLensLayer,
    critical_distance_um,
    focal_spot_loss,
    mutual_information_loss,
    mutual_information_loss_from_matrix,
    plot_field_evolution,
    select_propagator_method,
)

__all__ = [
    "fftconvolve",
    "Grid",
    "Spectrum",
    "Field",
    "OpticalLayer",
    "Sensor",
    "PropagationModel",
    "PropagationLayer",
    "OpticalModule",
    "PhaseMaskLayer",
    "AmplitudeMaskLayer",
    "ComplexMaskLayer",
    "ThinLensLayer",
    "IntensitySensor",
    "FieldReadout",
    "focal_spot_loss",
    "dct_basis_synthesis_matrix_2d",
    "build_full_sensing_matrix_dct",
    "randomized_svd",
    "total_coherence_loss",
    "total_coherence_loss_from_matrix",
    "mutual_information_loss",
    "mutual_information_loss_from_matrix",
    "ASMPropagator",
    "RSPropagator",
    "AutoPropagator",
    "Propagator",
    "critical_distance_um",
    "select_propagator_method",
    "plot_field_evolution",
]
