"""fouriax package."""

from fouriax.core.fft import fftconvolve
from fouriax.optics import (
    AmplitudeMaskLayer,
    ASMPropagator,
    AutoPropagator,
    ComplexMaskLayer,
    Field,
    FieldReadout,
    Grid,
    IntensitySensor,
    OpticalLayer,
    OpticalModule,
    PhaseMaskLayer,
    PropagationLayer,
    PropagationModel,
    RSPropagator,
    Sensor,
    Spectrum,
    ThinLensLayer,
    critical_distance_um,
    focal_spot_loss,
    plot_field_evolution,
    select_propagator_method,
)

__all__ = [
    "fftconvolve",
    "Grid",
    "Spectrum",
    "Field",
    "OpticalLayer",
    "Sensor",
    "PropagationModel",
    "PropagationLayer",
    "OpticalModule",
    "PhaseMaskLayer",
    "AmplitudeMaskLayer",
    "ComplexMaskLayer",
    "ThinLensLayer",
    "IntensitySensor",
    "FieldReadout",
    "focal_spot_loss",
    "ASMPropagator",
    "RSPropagator",
    "AutoPropagator",
    "critical_distance_um",
    "select_propagator_method",
    "plot_field_evolution",
]
