"""Core optics data models."""

from fouriax.optics.interfaces import IncoherentLayer, Monitor, OpticalLayer, Sensor
from fouriax.optics.layers import (
    AmplitudeMask,
    ComplexMask,
    FourierTransform,
    IncoherentImager,
    InverseFourierTransform,
    JonesMatrixLayer,
    KJonesMatrixLayer,
    KSpaceAmplitudeMask,
    KSpaceComplexMask,
    KSpacePhaseMask,
    OpticalModule,
    PhaseMask,
    ThinLens,
)
from fouriax.optics.meta_atoms import MetaAtomInterpolationLayer, MetaAtomLibrary
from fouriax.optics.model import Field, Grid, Intensity, Spectrum
from fouriax.optics.monitors import FieldMonitor, IntensityMonitor
from fouriax.optics.na_planning import (
    apply_na_limits,
    build_na_mask,
    collect_propagation_segments,
    collect_stops,
    effective_na,
    layer_with_na_if_supported,
    na_schedule,
    propagation_layer_view,
)
from fouriax.optics.noise import (
    GaussianNoise,
    PoissonGaussianNoise,
    PoissonNoise,
    SensorNoiseModel,
)
from fouriax.optics.propagation import (
    ASMPropagator,
    KSpacePropagator,
    RSPropagator,
    critical_distance_um,
    plan_propagation,
    recommend_nyquist_grid,
    select_propagator_method,
)
from fouriax.optics.sensors import Detector, DetectorArray

__all__ = [
    "Field",
    "Intensity",
    "Grid",
    "Spectrum",
    "SensorNoiseModel",
    "PoissonNoise",
    "GaussianNoise",
    "PoissonGaussianNoise",
    "Monitor",
    "IntensityMonitor",
    "FieldMonitor",
    "build_na_mask",
    "OpticalLayer",
    "IncoherentLayer",
    "Sensor",
    "OpticalModule",
    "PhaseMask",
    "AmplitudeMask",
    "ComplexMask",
    "FourierTransform",
    "InverseFourierTransform",
    "KSpacePhaseMask",
    "KSpaceAmplitudeMask",
    "KSpaceComplexMask",
    "JonesMatrixLayer",
    "KJonesMatrixLayer",
    "ThinLens",
    "IncoherentImager",
    "Detector",
    "DetectorArray",
    "MetaAtomLibrary",
    "MetaAtomInterpolationLayer",
    "ASMPropagator",
    "RSPropagator",
    "KSpacePropagator",
    "plan_propagation",
    "critical_distance_um",
    "select_propagator_method",
    "recommend_nyquist_grid",
    "propagation_layer_view",
    "collect_stops",
    "collect_propagation_segments",
    "effective_na",
    "na_schedule",
    "layer_with_na_if_supported",
    "apply_na_limits",
]
